# Generated by Django 4.1.1 on 2022-09-22 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartchurch', '0002_historicalbaptism'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emmergency_Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('relationship', models.CharField(blank=True, choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Sibling', 'Sibling'), ('Friend', 'Friend'), ('Spouse', 'Spouse'), ('Child', 'Child'), ('Others', 'Others'), ('No', 'No')], max_length=30, null=True)),
                ('specify', models.CharField(blank=True, max_length=255, null=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smartchurch.people')),
            ],
        ),
    ]
