# Generated by Django 4.1.1 on 2022-09-22 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartchurch', '0003_emmergency_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpeople',
            old_name='telephone',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='telephone',
            new_name='contact',
        ),
    ]
