# Generated by Django 4.1.1 on 2022-09-30 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartchurch', '0004_rename_telephone_historicalpeople_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpeople',
            old_name='profile_pic',
            new_name='profile_picture',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='profile_pic',
            new_name='profile_picture',
        ),
        migrations.AlterField(
            model_name='historicalprofile',
            name='church',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='smartchurch.church'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smartchurch.church'),
        ),
    ]
