# Generated by Django 4.1.1 on 2022-10-03 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartchurch', '0006_rename_specify_emmergency_contact_if_others_specify_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emmergency_contact',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must begin with 0 and contain only 10 digits', regex='^(0)\\d{9}$')]),
        ),
    ]
