# Generated by Django 4.1.1 on 2022-10-03 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartchurch', '0007_emmergency_contact_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emmergency_contact',
            old_name='contact_name',
            new_name='name',
        ),
    ]
