# Generated by Django 4.1.1 on 2022-11-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartchurch', '0009_alter_historicalpeople_status_alter_people_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpeople',
            name='name',
            field=models.CharField(blank=True, max_length=270, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='name',
            field=models.CharField(blank=True, max_length=270, null=True),
        ),
    ]
