# Generated by Django 4.1.1 on 2022-10-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_payment_vouchers_pv_details_historicalpv_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='tag',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], default='Income', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalaccounts',
            name='tag',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], default='Income', max_length=10),
        ),
    ]
