# Generated by Django 4.1.1 on 2022-10-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accounts_tag_historicalaccounts_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpv_details',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pv_details',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
