# Generated by Django 4.1.1 on 2022-10-04 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartchurch', '0009_alter_historicalpeople_status_alter_people_status'),
        ('accounts', '0005_historicalaccount_payables_account_payables'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_payables',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smartchurch.church'),
        ),
        migrations.AddField(
            model_name='historicalaccount_payables',
            name='church',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='smartchurch.church'),
        ),
    ]
