# Generated by Django 4.1.1 on 2022-10-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_general_ledger_transactionref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_vouchers',
            name='type',
            field=models.CharField(choices=[('Church', 'Church'), ('Credit Union', 'Credit Union'), ('Welfare', 'Welfare')], default='Church', max_length=25),
        ),
    ]
