# Generated by Django 4.1.1 on 2022-10-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_payment_vouchers_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_payables',
            name='type',
            field=models.CharField(choices=[('Church', 'Church'), ('Credit Union', 'Credit Union'), ('Welfare', 'Welfare')], default='Church', max_length=25),
        ),
        migrations.AddField(
            model_name='all_transaction',
            name='type',
            field=models.CharField(choices=[('Church', 'Church'), ('Credit Union', 'Credit Union'), ('Welfare', 'Welfare')], default='Church', max_length=25),
        ),
        migrations.AddField(
            model_name='general_ledger',
            name='type',
            field=models.CharField(choices=[('Church', 'Church'), ('Credit Union', 'Credit Union'), ('Welfare', 'Welfare')], default='Church', max_length=25),
        ),
        migrations.AddField(
            model_name='historicalaccount_payables',
            name='type',
            field=models.CharField(choices=[('Church', 'Church'), ('Credit Union', 'Credit Union'), ('Welfare', 'Welfare')], default='Church', max_length=25),
        ),
        migrations.AddField(
            model_name='historicalall_transaction',
            name='type',
            field=models.CharField(choices=[('Church', 'Church'), ('Credit Union', 'Credit Union'), ('Welfare', 'Welfare')], default='Church', max_length=25),
        ),
        migrations.AddField(
            model_name='historicalgeneral_ledger',
            name='type',
            field=models.CharField(choices=[('Church', 'Church'), ('Credit Union', 'Credit Union'), ('Welfare', 'Welfare')], default='Church', max_length=25),
        ),
    ]
