# Generated by Django 4.1.1 on 2022-10-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_account_payables_type_all_transaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpv_payment_history',
            name='type',
            field=models.CharField(choices=[('Church', 'Church'), ('Credit Union', 'Credit Union'), ('Welfare', 'Welfare')], default='Church', max_length=25),
        ),
        migrations.AddField(
            model_name='pv_payment_history',
            name='type',
            field=models.CharField(choices=[('Church', 'Church'), ('Credit Union', 'Credit Union'), ('Welfare', 'Welfare')], default='Church', max_length=25),
        ),
    ]
