# Generated by Django 4.1.1 on 2022-10-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_offerings_historicalofferings'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalofferings',
            name='offstatus',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('cancelled', 'cancelled'), ('void', 'void')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='offerings',
            name='offstatus',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('cancelled', 'cancelled'), ('void', 'void')], default='pending', max_length=20),
        ),
    ]
