# Generated by Django 4.1.1 on 2022-10-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_historicalofferings_offstatus_offerings_offstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='tag',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense'), ('Cash Eq', 'Cash Eq')], default='Income', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalaccounts',
            name='tag',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense'), ('Cash Eq', 'Cash Eq')], default='Income', max_length=10),
        ),
    ]
