# Generated by Django 4.1.1 on 2022-10-24 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0017_historicalaccount_receivables_account_receivables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_receivables',
            name='modified_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='armodifiedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='account_receivables',
            name='reference',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.offerings'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalaccount_receivables',
            name='reference',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.offerings'),
        ),
    ]
