# Generated by Django 4.1.1 on 2022-10-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_account_receivables_modified_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='tag',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense'), ('Cash-Eq', 'Cash-Eq'), ('Offerings', 'Offerings')], default='Income', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalaccounts',
            name='tag',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense'), ('Cash-Eq', 'Cash-Eq'), ('Offerings', 'Offerings')], default='Income', max_length=10),
        ),
    ]
