# Generated by Django 4.1.1 on 2022-10-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_accounts_tag_alter_historicalaccounts_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalofferings',
            name='offstatus',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('cancelled', 'cancelled'), ('Transact', 'Transact'), ('Reversed', 'Reversed'), ('void', 'void')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='offerings',
            name='offstatus',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('cancelled', 'cancelled'), ('Transact', 'Transact'), ('Reversed', 'Reversed'), ('void', 'void')], default='pending', max_length=20),
        ),
    ]
