# Generated by Django 4.1.1 on 2022-11-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_pledges_pledges_details_historicalpledges_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='tag',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense'), ('Cash-Eq', 'Cash-Eq'), ('Offerings', 'Offerings'), ('Pledges', 'Pledges')], default='Income', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalaccounts',
            name='tag',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense'), ('Cash-Eq', 'Cash-Eq'), ('Offerings', 'Offerings'), ('Pledges', 'Pledges')], default='Income', max_length=10),
        ),
    ]
