# Generated by Django 4.1.1 on 2022-11-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_accounts_tag_alter_historicalaccounts_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpledges',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pledges',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
