# Generated by Django 4.1.1 on 2022-11-17 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_historicalpledges_details_amount_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pledges_payment',
            name='church',
        ),
        migrations.RemoveField(
            model_name='pledges_payment',
            name='sub_code',
        ),
        migrations.DeleteModel(
            name='HistoricalPledges_payment',
        ),
        migrations.DeleteModel(
            name='Pledges_payment',
        ),
    ]
