# Generated by Django 4.1.1 on 2022-11-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_remove_pledges_payment_church_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpledges',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('cancelled', 'cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='pledges',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('cancelled', 'cancelled')], default='pending', max_length=20),
        ),
    ]
