# Generated by Django 4.1.1 on 2022-11-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_walfares_historicalwalfares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='tag',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense'), ('Cash-Eq', 'Cash-Eq'), ('Offerings', 'Offerings'), ('Pledges', 'Pledges'), ('Welfare', 'Welfare')], default='Income', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalaccounts',
            name='tag',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense'), ('Cash-Eq', 'Cash-Eq'), ('Offerings', 'Offerings'), ('Pledges', 'Pledges'), ('Welfare', 'Welfare')], default='Income', max_length=10),
        ),
    ]
