# Generated by Django 4.1.1 on 2022-11-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_alter_accounts_tag_alter_historicalaccounts_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalwalfares',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('cancelled', 'cancelled'), ('Walfare Posted', 'Welfare Posted')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='walfares',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('cancelled', 'cancelled'), ('Walfare Posted', 'Welfare Posted')], default='pending', max_length=20),
        ),
    ]
