# Generated by Django 4.1.1 on 2022-11-19 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('smartchurch', '0010_historicalpeople_name_people_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0033_transfers'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTransfers',
            fields=[
                ('id', models.CharField(db_index=True, max_length=100)),
                ('transaction_date', models.DateField()),
                ('tran_dec', models.CharField(blank=True, default='Transfer', max_length=300, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Comfirmed', 'Comfirmed'), ('Cancelled', 'Cancelled')], default='Comfirmed', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('type', models.CharField(choices=[('Church', 'Church'), ('Credit Union', 'Credit Union'), ('Welfare', 'Welfare')], default='Church', max_length=25)),
                ('created_date', models.DateField(blank=True, editable=False)),
                ('modified', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('church', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='smartchurch.church')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fromaccount_code', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.sub_accounts')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('toaccount_code', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.sub_accounts')),
            ],
            options={
                'verbose_name': 'historical transfers',
                'verbose_name_plural': 'historical transferss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
