# Generated by Django 4.1.1 on 2022-11-20 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('smartchurch', '0010_historicalpeople_name_people_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0034_historicaltransfers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='tag',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense'), ('Cash-Eq', 'Cash-Eq'), ('Offerings', 'Offerings'), ('Tithe', 'Tithe'), ('Pledges', 'Pledges'), ('Welfare', 'Welfare')], default='Income', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalaccounts',
            name='tag',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense'), ('Cash-Eq', 'Cash-Eq'), ('Offerings', 'Offerings'), ('Tithe', 'Tithe'), ('Pledges', 'Pledges'), ('Welfare', 'Welfare')], default='Income', max_length=10),
        ),
        migrations.CreateModel(
            name='Tithe',
            fields=[
                ('transaction_date', models.DateField()),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('cancelled', 'cancelled'), ('Tithe Posted', 'Tithe Posted')], default='pending', max_length=20)),
                ('church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smartchurch.church')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartchurch.people')),
                ('sub_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sub_accounts')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalTithe',
            fields=[
                ('transaction_date', models.DateField()),
                ('id', models.CharField(db_index=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('cancelled', 'cancelled'), ('Tithe Posted', 'Tithe Posted')], default='pending', max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('church', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='smartchurch.church')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='smartchurch.people')),
                ('sub_code', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.sub_accounts')),
            ],
            options={
                'verbose_name': 'historical tithe',
                'verbose_name_plural': 'historical tithes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
