# Generated by Django 4.1.1 on 2022-11-21 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartchurch', '0010_historicalpeople_name_people_name'),
        ('accounts', '0035_alter_accounts_tag_alter_historicalaccounts_tag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accumulated_fund',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], max_length=10)),
                ('open_date', models.DateField()),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('open_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('close_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smartchurch.church')),
            ],
        ),
        migrations.AddField(
            model_name='account_payables',
            name='account_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.accumulated_fund'),
        ),
        migrations.AddField(
            model_name='account_receivables',
            name='account_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.accumulated_fund'),
        ),
        migrations.AddField(
            model_name='all_transaction',
            name='account_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.accumulated_fund'),
        ),
        migrations.AddField(
            model_name='general_ledger',
            name='account_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.accumulated_fund'),
        ),
        migrations.AddField(
            model_name='historicalaccount_payables',
            name='account_period',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.accumulated_fund'),
        ),
        migrations.AddField(
            model_name='historicalaccount_receivables',
            name='account_period',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.accumulated_fund'),
        ),
        migrations.AddField(
            model_name='historicalall_transaction',
            name='account_period',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.accumulated_fund'),
        ),
        migrations.AddField(
            model_name='historicalgeneral_ledger',
            name='account_period',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.accumulated_fund'),
        ),
        migrations.AddField(
            model_name='historicalofferings',
            name='account_period',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.accumulated_fund'),
        ),
        migrations.AddField(
            model_name='historicalpledges',
            name='account_period',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.accumulated_fund'),
        ),
        migrations.AddField(
            model_name='historicaltithe',
            name='account_period',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.accumulated_fund'),
        ),
        migrations.AddField(
            model_name='historicaltransfers',
            name='account_period',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.accumulated_fund'),
        ),
        migrations.AddField(
            model_name='historicalwalfares',
            name='account_period',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.accumulated_fund'),
        ),
        migrations.AddField(
            model_name='offerings',
            name='account_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.accumulated_fund'),
        ),
        migrations.AddField(
            model_name='payment_vouchers',
            name='account_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.accumulated_fund'),
        ),
        migrations.AddField(
            model_name='pledges',
            name='account_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.accumulated_fund'),
        ),
        migrations.AddField(
            model_name='tithe',
            name='account_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.accumulated_fund'),
        ),
        migrations.AddField(
            model_name='transfers',
            name='account_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.accumulated_fund'),
        ),
        migrations.AddField(
            model_name='walfares',
            name='account_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.accumulated_fund'),
        ),
    ]
