# Generated by Django 4.1.1 on 2022-11-21 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smartchurch', '0010_historicalpeople_name_people_name'),
        ('accounts', '0036_accumulated_fund_account_payables_account_period_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAccumulated_fund',
            fields=[
                ('id', models.CharField(db_index=True, max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], max_length=10)),
                ('open_date', models.DateField()),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('open_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('close_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('church', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='smartchurch.church')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical accumulated_fund',
                'verbose_name_plural': 'historical accumulated_funds',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
