# Generated by Django 4.1.1 on 2022-11-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_historicalaccumulated_fund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accumulated_fund',
            name='status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Set To Close', 'Set To Close'), ('Closed', 'Closed')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalaccumulated_fund',
            name='status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Set To Close', 'Set To Close'), ('Closed', 'Closed')], max_length=50, null=True),
        ),
    ]
