# Generated by Django 4.1.1 on 2022-11-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_alter_accumulated_fund_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='group',
            field=models.CharField(choices=[('Revenue', 'Revenue'), ('Expense', 'Expense')], default='Revenue', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalaccounts',
            name='group',
            field=models.CharField(choices=[('Revenue', 'Revenue'), ('Expense', 'Expense')], default='Revenue', max_length=10),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='tag',
            field=models.CharField(choices=[('Revenue', 'Revenue'), ('Expense', 'Expense')], default='Expense', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalaccounts',
            name='tag',
            field=models.CharField(choices=[('Revenue', 'Revenue'), ('Expense', 'Expense')], default='Expense', max_length=10),
        ),
    ]
