# Generated by Django 4.1.1 on 2022-11-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_accounts_group_historicalaccounts_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='group',
            field=models.CharField(choices=[('Revenue', 'Revenue'), ('Expense', 'Expense'), ('Others', 'Others')], default='Revenue', max_length=10),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='tag',
            field=models.CharField(choices=[('Revenue', 'Revenue'), ('Expense', 'Expense'), ('Others', 'Others')], default='Expense', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalaccounts',
            name='group',
            field=models.CharField(choices=[('Revenue', 'Revenue'), ('Expense', 'Expense'), ('Others', 'Others')], default='Revenue', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalaccounts',
            name='tag',
            field=models.CharField(choices=[('Revenue', 'Revenue'), ('Expense', 'Expense'), ('Others', 'Others')], default='Expense', max_length=10),
        ),
    ]
