# Generated by Django 4.1.1 on 2022-11-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_alter_accounts_group_alter_accounts_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accumulated_fund',
            name='credit_open_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='accumulated_fund',
            name='walfare_close_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='accumulated_fund',
            name='walfare_open_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='historicalaccumulated_fund',
            name='credit_open_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='historicalaccumulated_fund',
            name='walfare_close_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='historicalaccumulated_fund',
            name='walfare_open_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='tag',
            field=models.CharField(choices=[('Expense', 'Expense'), ('Cash-Eq', 'Cash-Eq'), ('Offerings', 'Offerings'), ('Tithe', 'Tithe'), ('Pledges', 'Pledges'), ('Welfare', 'Welfare')], default='Expense', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalaccounts',
            name='tag',
            field=models.CharField(choices=[('Expense', 'Expense'), ('Cash-Eq', 'Cash-Eq'), ('Offerings', 'Offerings'), ('Tithe', 'Tithe'), ('Pledges', 'Pledges'), ('Welfare', 'Welfare')], default='Expense', max_length=10),
        ),
    ]
